vich_uploader:
    db_driver: orm

    mappings:
        vehicle:
            uri_prefix: /Pictures/upload/vehicle
            upload_destination: '%kernel.project_dir%/public/Pictures/upload/vehicle'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
