controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

main:
    path: /acceuil
    controller: App\Controller\MainController::index

services:
    path: /services
    controller: App\Controller\ServicesController::index

vehicle:
    path: /vehicules
    controller: App\Controller\VehicleController::index

contact:
    path: /contact
    controller: App\Controller\ContactController::index